### ISSUE TITLE
Install Guide link on main Readme.rst goes to ZEHICLE

### ISSUE THREAD

**Issue by galthaus** [digitalrebar/doc#1]

**Comment by zehicle** [comment]
oh!  I got the install page in the right place.  Will fix !

On Wed, Sep 2, 2015 at 8:58 AM, Greg Althaus <notifications@github.com>
wrote:

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/digitalrebar/doc/issues/1>.
>



-- 
Rob
____________________________
Rob Hirschfeld, 512-773-7522
RackN CEO/Founder (rob@rackn.com)

I am in CENTRAL (-6) time
http://robhirschfeld.com
twitter: @zehicle, github: zehicle

**Comment by zehicle** [comment]
fixed

**Comment by zehicle** [comment]
Hi,

I'd like to add you to my professional network on LinkedIn.

- Rob

Confirm that you know Rob: https://www.linkedin.com/e/v2?e=0-im6cz9pf-v2&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=Jp6t9wvk&invitationId=6118771172512452608








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-im6cz9pf-v2&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQF854avnMXsjQAAAVOo-Gvc82TwmXTkzkL6JhcpRYL_q8jN3w9aJa_kzt_g-lZz6XlQQzSTnZyDTKrna_TJgiPIUqth9ElDsYTVU5bhKXPRAFHb0fpHvVkUnSqA01LhIWynDL5tTF_9yLbFOs2593JTKL4920tsycylxGgcESb10sIx_XmcSXRyHRUe22zpfoGL&eid=0-im6cz9pf-v2


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-im6cz9pf-v2&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by zehicle** [comment]
Rob Hirschfeld would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=wc8i2s-imfatzg5-kg&a=preRegInvite&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=Jp6t9wvk&invitationID=6118771172512452608

View Rob Hirschfeld&#39;s profile: https://www.linkedin.com/e/v2?e=wc8i2s-imfatzg5-kg&a=preRegInvite&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=Jp6t9wvk&invitationID=6118771172512452608





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=wc8i2s-imfatzg5-kg&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=wc8i2s-imfatzg5-kg&loid=AQGiToWk6TkI_AAAAVPJ-EgxDGbmWJtUgeiWMWSes7T2diJV6D-Rc8N4TuFzH9KNaGZkeTvnLvsd2XSsIiGs7x1vkt1iNeVOXa1M2VYV7wsrc8gpRqSJAl7Q5IX7yf8V2QV_CSNOfko3hOtTJUmREEeALI8lIjOCZ1Wbvp6lkPEHVQos7j-yAfqae99LfUsZBEJt

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=wc8i2s-imfatzg5-kg&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by zehicle** [comment]
Rob Hirschfeld would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=wc8i2s-impb4wsk-o5&a=preRegInvite&ek=second_guest_reminder_01&li=13&m=hero&ts=accept_text&sharedKey=Jp6t9wvk&invitationID=6118771172512452608

View Rob Hirschfeld&#39;s profile: https://www.linkedin.com/e/v2?e=wc8i2s-impb4wsk-o5&a=preRegInvite&ek=second_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=Jp6t9wvk&invitationID=6118771172512452608





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=wc8i2s-impb4wsk-o5&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=15&m=unsub&ts=HTML&eid=wc8i2s-impb4wsk-o5&loid=AQFzdeKq1YNyDQAAAVPuBMVDt7tKvUpSDEOIuWv3QdTPMfxHXHvuLvz81dswte5iwwjALPIvRJrYOkikqim4luixkyBb_TBGLRdrbei708vkVK-lrnyvvDg3IH2o0siryPNztFjUoKuyX6e7jsedxydAZm-fnDZDum8WXiO6k0dtKzcU-0OsT2w8pIHTrekihgjF

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=wc8i2s-impb4wsk-o5&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
