### ISSUE TITLE
Some images have incorrect case causing them to 404

### ISSUE THREAD

**Issue by Meshiest** [digitalrebar/doc#94]
examples:

 * [5.1.2.1's overview image](http://digital-rebar.readthedocs.io/en/latest/user/webux/overview.html)
 * [5.1.3's deployments image](http://digital-rebar.readthedocs.io/en/latest/user/webux/deployment.html)
 * [5.1.5's provider image](http://digital-rebar.readthedocs.io/en/latest/user/webux/providers.html)

**Comment by StephenTames** [comment]
FIXED IN #102
